# Generated by Django 5.0.4 on 2024-04-08 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_cusromer_customer_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
